# Loading the data

In [6]:
# import the iris dataset from sklearn
from sklearn.datasets import load_iris

In [7]:
iris = load_iris()

In [21]:
# used a capital X because it holds a matrix 
# Feature matrix
X = iris.data

In [22]:
# used a small y because is a vector
# Label vector
y = iris.target

In [10]:
# observation and shape of the data
X.shape

(150, 4)

In [11]:
# observation and shape of the data
y.shape

(150,)

# Modelling Pattern

In [12]:
# import the KNeighborsClassifier class from sklearn.neighbors
from sklearn.neighbors import KNeighborsClassifier

In [18]:
# use 1 as your k value. As your tuning/hyper parameter
# Instanciate the estimator
knn = KNeighborsClassifier(n_neighbors=1)

In [19]:
knn

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=1, p=2,
           weights='uniform')

In [20]:
# fit the data to the classifier
knn.fit(X, y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=1, p=2,
           weights='uniform')

In [16]:
# use data outside the model
out_of_sample_data = [3, 5, 4, 2], [5, 4, 3, 2]
knn.predict(out_of_sample_data)

array([2, 1])

In [17]:
# use data in model
in_sample_data = [4.9, 3.,  1.4, 0.2], [4.7, 3.2, 1.3, 0.2]
knn.predict(in_sample_data)

array([0, 0])

# Using a different value for K

In [23]:
# 5 is the default k value
knn = KNeighborsClassifier()

In [24]:
knn

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [25]:
# fit the data to the classifier
knn.fit(X, y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [26]:
# use data outside the model
knn.predict(out_of_sample_data)

array([1, 1])

In [27]:
# use data in model
in_sample_data = [4.9, 3.,  1.4, 0.2], [4.7, 3.2, 1.3, 0.2]
knn.predict(in_sample_data)

array([0, 0])

# Results without model training

In [28]:
no_fit = KNeighborsClassifier()

In [29]:
no_fit

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [30]:
# you have to fit the data first
no_fit.predict(out_of_sample_data)

NotFittedError: Must fit neighbors before querying.

# Using a different classification model

In [31]:
from sklearn.linear_model import LogisticRegression

In [32]:
logreg = LogisticRegression()

In [33]:
logreg

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [34]:
# fit data to LogisticRegression method
logreg.fit(X, y)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [35]:
# use data outside the model
logreg.predict(out_of_sample_data)

array([2, 0])

In [36]:
# use data in model
in_sample_data = [4.9, 3.,  1.4, 0.2], [4.7, 3.2, 1.3, 0.2]
knn.predict(in_sample_data)

array([0, 0])

In [37]:
logreg.predict([5, 4, 3, 2])

ValueError: Expected 2D array, got 1D array instead:
array=[5 4 3 2].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.